name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  rebuild_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
          cd ReStore-It-Frontend
          docker image build . --file Dockerfile -t restoreit-business:latest 
